appname = Agroempleo_vacantes_MID
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

host_api=http://localhost:8083/v1/
host_api2=http://localhost:8080/v1/
host_api3=http://localhost:8081/v1/
host_api4=http://localhost:8084/v1/
host_api5=http://localhost:8087/v1/
host_api6=http://localhost:8087/v1/postulaciones?query=IdEmpleo:


