appname = Agroempleo_vacantes_MID
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 

host_api=http://localhost:8083/v1/
host_api2=http://localhost:8080/v1/



